# File name: .github/workflows/job_bot.yml
name: Run Job Application Bot

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  apply:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run bot
      env:
        GREENHOUSE_API_KEY: ${{ secrets.GREENHOUSE_API_KEY }}
        NAME: ${{ secrets.NAME }}
        EMAIL: ${{ secrets.EMAIL }}
        RESUME_URL: ${{ secrets.RESUME_URL }}
      run: python job_bot.py
